### PR TITLE
Create pt_br.json

### PR DESCRIPTION
**Pull request by Brun333rp**
Brazilian portuguese localization

### CODE REVIEW

**Comment by Brun333rp** [comment]
so, the translation is already done and I'm waiting for someone to merge it

**Comment by Brun333rp** [comment]
still waiting...

**Comment by cech12** [comment]
I know. It won't go any faster with such comments ...

**Comment by Brun333rp** [comment]
ok? I didn't said it to offend you. it's just that it could be already merged. you don't need to take that personaly

**Comment by Brun333rp** [comment]
I just said "still waiting", why is that offensive for you?

**Comment by cech12** [comment]
I do all of this in my free time and such statements are just annoying.

**Comment by Brun333rp** [comment]
lol, you indeed didn't deserved my contributions

**Comment by cech12** [comment]
Ok

**Pull request closed without merging**
